services:
  etcd01:
    image: quay.io/coreos/etcd:latest
    restart: on-failure
    hostname: etcd-01
    command:
      - etcd
      - --name=etcd01
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd01:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd01:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster1
    volumes:
      - etcd01vol:/data.etcd:rw
      - ./certs:/certs:ro
    networks:
      - etcd
  etcd02:
    image: quay.io/coreos/etcd:latest
    restart: on-failure
    hostname: etcd02
    command:
      - etcd
      - --name=etcd02
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd02:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd02:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster1
    volumes:
      - etcd02vol:/data.etcd:rw
      - ./certs:/certs:ro
    networks:
      - etcd
  etcd03:
    image: quay.io/coreos/etcd:latest
    restart: on-failure
    hostname: etcd03
    command:
      - etcd
      - --name=etcd03
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd03:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd03:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster1
    volumes:
      - etcd03vol:/data.etcd:rw
      - ./certs:/certs:ro
    networks:
      - etcd

volumes:
  etcd01vol:
    driver: local
  etcd02vol:
    driver: local
  etcd03vol:
    driver: local

networks:
  etcd:
    driver: bridge
