services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    restart: always
    deploy:
      mode: global
    ports:
      - "5672:5672"

  postgres:
    image: postgres:alpine
    restart: always
    deploy:
      mode: global
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGPASSWORD: $uper$strongPa$$word
    ports:
      - "5432:5432"
    # specify separate db schemas for Identity service, Blogging service, Comments service and EventStore
    #volumes:
    #- /initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: always
    deploy:
      mode: global
    ports:
      - "6379:6379"

  discovery-api:
    image: blog/discovery-api
    build:
      context: .
      dockerfile: ./Services/Discovery/Discovery.API/Dockerfile
    deploy:
      mode: global
    depends_on:
      - rabbitmq
      - redis
      # - eventstore-api
    ports:
      - "7001:7001"

  emailing-api:
    image: blog/emailing-api
    build:
      context: .
      dockerfile: ./Services/Emailing/Emailing.API/Dockerfile
    scale: 5
    depends_on:
      - rabbitmq
      - discovery-api
    ports:
      - "7017-7021:80"

  identity-api:
    image: blog/identity-api
    build:
      context: .
      dockerfile: ./Services/Identity/Identity.API/Dockerfile
    scale: 5
    depends_on:
      - rabbitmq
      - postgres
      - discovery-api
      - emailing-api
    ports:
      - "7002-7006:80"

  blogging-api:
    image: blog/blogging-api
    build:
      context: .
      dockerfile: ./Services/Blogging/Blogging.API/Dockerfile
    scale: 5
    depends_on:
      - rabbitmq
      - postgres
      - discovery-api
      - emailing-api
    ports:
      - "7007-7011:80"

  comments-api:
    image: blog/comments-api
    build:
      context: .
      dockerfile: ./Services/Comments/Comments.API/Dockerfile
    scale: 5
    depends_on:
      - rabbitmq
      - postgres
      - discovery-api
      - emailing-api
    ports:
      - "7012-7016:80"

  webgateway-api:
    image: blog/webgateway-api
    build:
      context: .
      dockerfile: ./Gateways/WebGateway.API/Dockerfile
    deploy:
      mode: global
    depends_on:
      - rabbitmq
      - discovery-api
      - identity-api
      - blogging-api
      - comments-api
      - emailing-api
    ports:
      - "7000:7000"
  # eventstore-api:
  #   image: blog/eventstore-api
  #   build:
  #     context: .
  #     dockerfile: ./Services/EventStore/EventStore.API/Dockerfile
  #   depends_on:
  #     - rabbitmq
  #     - postgres
