services:
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: on-failure
    deploy:
      mode: global
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:alpine
    restart: on-failure
    deploy:
      mode: global
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGPASSWORD: SuperStrongPassword
    ports:
      - '5432:5432'
    # specify separate db schemas for Identity service, Blogging service, Comments service and EventStore
    #volumes:
    #- /initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: on-failure
    deploy:
      mode: global
    ports:
      - '6379:6379'

  discovery-api:
    image: blog/discovery-api
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Discovery/Discovery.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    deploy:
      mode: global
    depends_on:
      - rabbitmq
      - redis
      # - eventstore-api
    ports:
      - '7001:7001'

  emailing-api:
    image: blog/emailing-api
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Emailing/Emailing.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - rabbitmq
      - discovery-api
    ports:
      - '7017-7021:80'

  identity-api:
    image: blog/identity-api
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - rabbitmq
      - postgres
      - discovery-api
      - emailing-api
    ports:
      - '7002-7006:80'

  blogging-api:
    image: blog/blogging-api
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Blogging/Blogging.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - rabbitmq
      - postgres
      - discovery-api
      - emailing-api
    ports:
      - '7007-7011:80'

  comments-api:
    image: blog/comments-api
    restart: on-failure
    build:
      context: .
      dockerfile: Services/Comments/Comments.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - rabbitmq
      - postgres
      - discovery-api
      - emailing-api
    ports:
      - '7012-7016:80'

  webgateway-api:
    image: blog/webgateway-api
    restart: on-failure
    build:
      context: .
      dockerfile: Gateways/WebGateway.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    deploy:
      mode: global
    depends_on:
      - rabbitmq
      - discovery-api
      - identity-api
      - blogging-api
      - comments-api
      - emailing-api
    ports:
      - '7000:7000'
  # eventstore-api:
  #   image: blog/eventstore-api
  #   build:
  #     context: .
  #     dockerfile: ./Services/EventStore/EventStore.API/Dockerfile
  #   environment:
  #    ASPNETCORE_ENVIRONMENT: Development
  #   depends_on:
  #     - rabbitmq
  #     - postgres
