services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:80"
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGPASSWORD: $uper$strongPa$$word
    ports:
      - "5432:80"
    # specify separate db schemas for Identity service, Blogging service, Comments service and EventStore
    #volumes:
    #- /initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:80"

  identity-api:
    image: blog/identity-api
    build:
      context: .
      dockerfile: Services/Identity/Identity.API
    depends_on:
      - rabbitmq
      - postgres

  blogging-api:
    image: blog/blogging-api
    build:
      context: .
      dockerfile: Services/Blogging/Blogging.API
    depends_on:
      - rabbitmq
      - postgres

  comments-api:
    image: blog/comments-api
    build:
      context: .
      dockerfile: Services/Comments/Comments.API
    depends_on:
      - rabbitmq
      - postgres

  emailing-api:
    image: blog/emailing-api
    build:
      context: .
      dockerfile: Services/Emailing/Emailing.API
    depends_on:
      - rabbitmq

  eventstore-api:
    image: blog/eventstore-api
    build:
      context: .
      dockerfile: Services/EventStore/EventStore.API
    depends_on:
      - rabbitmq
      - postgres

  discovery-api:
    image: blog/discovery-api
    build:
      context: .
      dockerfile: Services/Discovery/Discovery.API
    depends_on:
      - rabbitmq
      - redis
      - identity-api
      - blogging-api
      - comments-api
      - emailing-api
      - eventstore-api

  webgateway-api:
    image: blog/webgateway-api
    build:
      context: .
      dockerfile: Gateways/WebGateway.API
    depends_on:
      - rabbitmq
      - discovery-api
